### ISSUE TITLE
Showing EP in Cycles

### ISSUE THREAD

**Issue by zeffii** [MonZop/BioBlender#11]
![image](https://cloud.githubusercontent.com/assets/619340/6020169/f5752ac6-aba8-11e4-9a15-17250ea348d6.png)

looking forward to seeing cycles render these..

**Comment by MonZop** [comment]
How did you manage to get the lines without the surface?
The logic is:
Use atomic positions and atomic charge to calculate ptential in the molecular volume (by PDB2PQR and APBS): this generates a file .dx;
select relevant points on molecular surface (MonteCarlo procedure);
Draw lines in both directions starting from selected points;
End lines when inside the surface (in one direction) abd at value =0 (in other direction)

**Comment by zeffii** [comment]
I imported the pdb, then opened the EP panel and pressed 'Show EP'. I wasn't aware that EP relied on the surface mesh (unless what you see in the image to the right is incorrect, it doesn't rely on surface being explicitly created ) it's a part of the code I haven't looked at in depth yet.

**Comment by MonZop** [comment]
The surface must be created, as it is necessary  for the selection of lines. However, it might not be necessary that it is imported into Blender, and shown. (as in the case you just show)

**Comment by zeffii** [comment]
right, it is probably done behind the scenes in some temporary file..

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/6021927/891d9244-abb9-11e4-8a9e-fb244c597241.png)

**Comment by MonZop** [comment]
Looks great!
The lines are supposed to be paths for animated particles: they must flow in the direction Positive' to Negative, in order to provide information on the direction of the field (the intensity of the field is suggwsed by the N of lines, i.e. of flowing particles).
In this case, the DNA has a quite strong negative charge (due to all the phosphates), and most particles will look like needles atracted towards the DNA, especially the orange spheres

**Comment by zeffii** [comment]
larger render, could use more subdivisions on the curves
( i like to render occasionally to keep me motivated )
![pretty_pics](https://cloud.githubusercontent.com/assets/619340/6022432/fc3788ea-abbc-11e4-9a36-6ed0e0005648.png)

**Comment by zeffii** [comment]
![ep_works](https://cloud.githubusercontent.com/assets/619340/6043852/938c5b26-ac8f-11e4-910f-8baadbaab7d4.gif)

**Comment by MonZop** [comment]
Good! 
I also tried to render EP, (not in cycles, just in the 3D viewport), and I notice that  some curves never get the particles on them. It seems to be the case also in your example.

**Comment by zeffii** [comment]
OK, another thing to look into!

**Comment by MonZop** [comment]
Do you have a skype contact, or a direct email, so I can address to you directly with some issues that might be more easily discussed directly, and that might not be of interest for everyone?
My skype is Monzop and my email is mzoppe@ifc.cnr.it

**Comment by zeffii** [comment]
![terraform2](https://cloud.githubusercontent.com/assets/619340/6186547/05f72046-b37b-11e4-9c70-62ac25459bfa.png)
using hair

**Comment by MonZop** [comment]
cool!

**Comment by MonZop** [comment]
This example illistrate very well the difficulty of showing the Electrostatic potential: the origin of the line is located at a charged point, almost always inthe protein (or DNA). It can be ewither positive or negative. 
The lines will run 
a) towards another charge of opposite sign (if present at reasonable distance, it can also be another protein); in this case thw line bends when it 'senses' the other charge;
b) towards the space around it (which is water with some salts dissolved); in this case theline is just about straight;
c) If there is another protein with a charge of the same sign, the two will repel each other, and the lines will make a turn to run parallel. 

The example with hair is very intersting, because it looks really nice, but gives a (wrong) impression of being generated at the (positive) end, especially visible in the right upper corner. It is a case of line generated by a negative charge. If you do this with DNA, you will see even more this effect.

**Comment by zeffii** [comment]
Here the node material colour gradient is taken from the hair radius at each point over the length of the hair. For effect I exaggerated the difference in base-width vs tip-width. red at the base (origin of the curve) blue at the tip., all values are arbitrary here. ..just explorations.

![image](https://cloud.githubusercontent.com/assets/619340/6186987/4ab6f4e4-b381-11e4-8b66-1a3ad63bed5a.png)

**Comment by MonZop** [comment]
The updating of the molecule for EP in a moving protein works OK, see https://vimeo.com/119557005 pw EP_157

**Comment by zeffii** [comment]
vimeo says the pw is incorrect

**Comment by MonZop** [comment]
Sorry, now it is correct
